### PR TITLE
Modernize headers

### PR DESCRIPTION
**Pull request by Xeeynamo**
Extract some commits out of #1701 and avoid the part that will lead to a build failure (fixed in #1738).

Now every header uses `OVL_EXPORT`.

### CODE REVIEW

**Comment by sozud** [comment]
Looks like zero sized array issues
```

D:\a\sotn-decomp\sotn-decomp\src\st\wrp\header.c(11,14): error C2133: 'spriteBanks': unknown size [D:\a\sotn-decomp\sotn-decomp\pc\core.vcxproj]
D:\a\sotn-decomp\sotn-decomp\src\st\wrp\header.c(12,16): error C2133: 'cluts': unknown size [D:\a\sotn-decomp\sotn-decomp\pc\core.vcxproj]
D:\a\sotn-decomp\sotn-decomp\src\st\wrp\header.c(13,18): error C2133: 'rooms_layers': unknown size [D:\a\sotn-decomp\sotn-decomp\pc\core.vcxproj]
D:\a\sotn-decomp\sotn-decomp\src\st\wrp\header.c(14,17): error C2133: 'gfxBanks': unknown size [D:\a\sotn-decomp\sotn-decomp\pc\core.vcxproj]
```

**Review by sozud — APPROVED** [review]
Seems good once it compiles

**Comment by sozud** [comment]
> I cannot come up with any fix for that unfortunately. I am hitting another wall.

Can the tool not detect the size of the arrays and emit a `#define SPRITE_BANKS_SIZE` to avoid these?

**Comment by sozud** [comment]
It looks like some of the CI steps are being skipped due to the conflicts?

**Review by sozud — APPROVED** [review]
Looks good, thanks for fixing the msvc issues
